# 1. Adım: .NET SDK kullanarak projeyi derleme
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Proje dosyalarını kopyala ve restore et
COPY ["WebAPI/WebAPI.csproj", "WebAPI/"]
COPY ["Core/Core.csproj", "Core/"]
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]
COPY ["Application/Application.csproj", "Application/"]
RUN dotnet restore "WebAPI/WebAPI.csproj"

# Tüm kodları kopyala ve derle
COPY . .
WORKDIR "/src/WebAPI"
RUN dotnet publish "WebAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

# 2. Adım: Sadece çalışma zamanı (Runtime) kullanarak uygulamayı çalıştırma
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Render'ın port ayarı için varsayılanı tanımlıyoruz
ENV ASPNETCORE_URLS=http://+:10000

ENTRYPOINT ["dotnet", "WebAPI.dll"]